apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axual-debug-gp.fullname" . }}
  labels:
    {{- include "axual-debug-gp.labels" . | nindent 4 }}
  namespace: kafka
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "axual-debug-gp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "axual-debug-gp.selectorLabels" . | nindent 8 }}
    spec:
      
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "axual-debug-gp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts: 
            - name: static-volume
              mountPath: /cache-folder
            {{- range .Values.secretsMounts }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        - name: static-volume
          emptyDir: {} 
        {{- range .Values.secretsMounts }}
        - name: {{ .name }}-volume
          secret:
            secretName: {{ .name }}
        {{- end }}    
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
